#!/bin/bash
#
# @Author Naval
# this command will enable and disable the proxy
#set -vx
clear
file_path="$HOME/.gradle/gradle.properties"
chmod 755 $file_path
file_size=$(wc -l $file_path)
file_size=$(cut -d ' ' -f 1 <<<$file_size)
cat >$file_path << 'EOL'
## For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
#
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx1024m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true
#Fri Dec 20 22:55:19 IST 2019
android.enableBuildCache=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
EOL
if [ "$file_size" = "26" ]
then
echo "Proxy disabled"
else
cat >>$file_path << 'EOL'
systemProp.http.proxyUser=UserName
systemProp.http.proxyPassword=
systemProp.https.proxyPassword=
systemProp.https.proxyHost=127.0.0.1
systemProp.http.proxyPort=8080
systemProp.http.proxyHost=127.0.0.1
systemProp.https.proxyPort=8080
systemProp.https.proxyUser=UserName
EOL
echo "Proxy enabled"
fi
chmod 644 $file_path
#set +vx
